version: '3'

services:
  database:
    container_name: database
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  php:
    container_name: php
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - SYMFONY_PHPUNIT_VERSION=9.5
      - XDEBUG_MODE=coverage
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
    volumes:
      - .:/var/www
      - /var/www/var
      - /var/www/vendor
      - /var/www/bin/.phpunit

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    depends_on:
      - php
    ports:
      - "80:80"
