App\Domain\Model\Room\Room:
    type: entity
    repositoryClass: App\Infrastructure\Persistence\Doctrine\Repository\RoomRepository
    table: room
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            lenght: 50